### ISSUE TITLE
Same-Site Links: disable new target? allow absolute URLs without system forcibly prepending http://?

### ISSUE THREAD

**Issue by SevenZark** [brijeshb42/medium-draft#114]
I'm using this library for a simple content management system. Thus, I will frequently want users to be able to put links in their documents that refer to the same site on which the content appears.

I have two issues with this:

1. By default, it seems that medium-draft renders out a target="_blank" attribute on the <a> tag. This is undesirable behavior for a content management system when trying to link to another page the same site, since it always causes the target page to open in a new tab or window. Also, it strikes me as a rather undesirable default, regardless. I'd prefer that be an option of some kind. Most of the time opening new tabs/windows on a link click is kind of a bad user experience.

2. Also when rendering, medium-draft seems to always prepend 'http://' to every <a> link. This makes it impossible to allow links to the same domain without always manually typing in the full domain name. It also creates challenges for testing and development environments when using the content. My expectation was that the link would not try to be so 'helpful' by always prepending the http, but rather let me put in exactly what I want for the link src. I'd humbly suggest this makes more sense as a default. As it stands now, a link like "/about-us" won't work.

**Comment by brijeshb42** [comment]
Added a prop in version `0.5.6`. You can pass a `processURL` prop to the editor which is passed the url entered by the user. For your use case, the simplest can be -

```jsx
<Editor
    ...
    processURL={(url) => url}
    ...
 />
```

**Comment by SevenZark** [comment]
Thanks for your response! Will this be applied to any link the user creates inside the editor?

**Comment by brijeshb42** [comment]
Yes. Every new link the user adds will be passed to this function first. Whatever is returned will be saved in the state. 8:44 PM, November 17, 2017, Dave M <notifications@github.com>:Thanks for your response! Will this be applied to any link the user creates inside the editor?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-

**Comment by SevenZark** [comment]
Great, thanks for the info!

**Comment by SevenZark** [comment]
I just tried this out, and it seems to work well, except it still forces target="_blank" on the rendered link. Any way around that?

**Comment by brijeshb42** [comment]
Checkout https://github.com/brijeshb42/medium-draft/blob/master/src/exporter.js to learn how to customize html output for a tag1:24 AM, December 7, 2017, Dave M <notifications@github.com>:I just tried this out, and it seems to work well, except it still forces target="_blank" on the rendered link. Any way around that?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-

**Comment by SevenZark** [comment]
Thanks a ton for your help! Got everything working the way I want now.
