### ISSUE TITLE
Editor loses focus when clicking to add link

### ISSUE THREAD

**Issue by desktp** [brijeshb42/medium-draft#136]
When trying to add a link or remove a link from a selection, the editor loses focus, causing the selection to be lost sometimes and the add/remove link operation to fail. Is there a way to customize/override the action taken to `preventDefault` maybe? 
In my use case I save the contents to a backend on blur, then fetch it again. The `editorState` is refreshed with 
```
      const blockData = JSON.parse(value);
      editorState = EditorState.push(this.state.editorState, convertFromRaw(blockData));
```
so the selection should be maintained, correct?

**Comment by brijeshb42** [comment]
With the above case, the selection cannot be maintained since you are completely replacing the editorstate and all the previous block keys that were there are now replaced with new ones. If the block keys are same, you can save the current selection before applying new contents and use the `forceSelection` method of `EditorState`.

**Comment by desktp** [comment]
Indeed, just grabbing the old selection and applying it again worked.
