### ISSUE TITLE
Optimistic Updates

### ISSUE THREAD

**Issue by jaspersorrio** [brijeshb42/medium-draft#97]
Hi @brijeshb42, thank you for this library!! Love the openness and functionality of it. Appreciate all the example code.

Would like to ask how can one update a block?

For example, in your [readme](https://github.com/brijeshb42/medium-draft/blob/master/README.md#customizing-side-buttons), you showed how one can update the editor state by passing `addNewBlock(...)` to `setEditorState` after an image has finished uploading to the server.

But what if I want to perform optimistic updates? For example show an uploading msg or placeholder image while uploading to the server then updating the block with the actual image once the image has been successfully updated to the server.

Would like to know how can one proceed to do something like that. Thank you for all the help! 😊

EDIT: Also, how can i pass extra props into the sidebar component? Thank You!

**Comment by brijeshb42** [comment]
I have actually implemented what you are talking about in one of my editors. Altough it works fine in itself, but the undo functionality will result in a slightly erroneous behaviour.
In the example, image is added to editor only once the url is available. You can add the image before that though. When you get the file instance -

* you create an object url of the image
* use `addNewBlock` with the `objectUrl` as `src`.
* image will be immediately shown inside the editor. add another `progress` attribute alongwith `src` if you want to show some kind of progress or just that the image is uploading.
* save the `key` of the new image block
* once image is uploaded and you get the url, replace the `src` of data of block that has the `key` that you saved in last step. also update the `progress` key.

You can have a look at the demo editor [here](https://editor.bittu.me/). Drop an image file on the editor. The image uploading will fail due to backend issue, but you'll get an idea.

**Comment by jaspersorrio** [comment]
Wow @brijeshb42!! Thanks for such a great explanation.  

I have 2 questions. How do i obtain `key` & how do i replace the `src`? Is there a method to do that?

Thank you!

**Comment by brijeshb42** [comment]
Before adding the image block, get current block's key -

```js
import {getCurrentBlock} from 'medium-draft';

const es = yourEditorState;
const blockKey = getCurrentBlock(es).getAnchorKey()
```

Now add the image -

```js
import {addNewBlock, updateDataOfBlock} from 'medium-draft';

const file = //from file button or dropped
const tempSrc = URL.createObjectURL(file);
// If using addNewBlock, same key is retained
const newEs = addNewBlock (es, Block.Image, {src: tempSrc, progress: 0});
// call onChange(newEs)
const imageBlock = newEs.getCurrentContent().getBlockForKey(blockKey);
startUpload ({
  file,
  onSuccess: (response) => {
    const esWithImageSrc = updateDataOfBlock(newEs, imageBlock, {src: response.url, progress: 100});
   // call onChange(esWithImageSrc);
  },
  onError: (err) => {
     // remove the temp image here if error.
  }
});
```
